1) Make a 5x5 matrix filled with random integers between [0, 10)

In [52]:
import numpy as np
from numpy import random
rng = random.default_rng(42)

In [53]:
M = rng.integers(0, 10, (5, 5))
print(M)

[[0 7 6 4 4]
 [8 0 6 2 0]
 [5 9 7 7 7]
 [7 5 1 8 4]
 [5 3 1 9 7]]


In [54]:
a = ["A", 2, 3]
a = np.array(a)
print(a)

['A' '2' '3']


2) Print the last two rows

In [55]:
print(M[3:][:])

[[7 5 1 8 4]
 [5 3 1 9 7]]


3) Print the middle column only

In [56]:
print(M[:,2])

[6 6 7 1 1]


4) Print the bottom left 2x2 minor

In [57]:
print(M[-2:, 0:2])

[[7 5]
 [5 3]]
