In [1]:
import numpy as np
import pandas as pd

# Midterm Review #1

In [2]:
# Array with integers 10-20 inclusive
a = np.arange(10, 21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])
#a * b?
# Ans: numpy array of [4, 10, 18]

In [4]:
arr = np.arange(10)
slc = arr[1::2]
print(slc)

[1 3 5 7 9]


In [5]:
x=np.array([2,4,6,8,10])
print(f"mean: {np.mean(x)}")
print(f"sd: {np.std(x)}")


mean: 6.0
sd: 2.8284271247461903


In [6]:
a = np.arange(12)
a = a.reshape((3, 4))
print(a)
print(a[1,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]


In [15]:
df = pd.DataFrame({'name':['Alice','Bob','Charlie','David'],'age':[25,30,35,40],'city':['NY','LA','Chicago','Houston']})
df.head()

name  age     city
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40  Houston

In [16]:
df[["name", "city"]]



name     city
0    Alice       NY
1      Bob       LA
2  Charlie  Chicago
3    David  Houston

In [9]:
rows = df[df["age"] > 30]
print(rows)

      name  age     city
2  Charlie   35  Chicago
3    David   40  Houston


In [10]:
df=pd.DataFrame({'team':['A','A','B','B','C'],'points':[10,15,10,20,30]})

means = df.groupby("team").mean()
# Should be 12.5, 15, 30
means

points
team        
A       12.5
B       15.0
C       30.0

In [17]:
df=pd.DataFrame({'name':['Anna','Ben','Cara'],'score':[88,92,79]})

df["grade"] = df["score"].apply(lambda x: "Pass" if x >= 85 else "Fail")
# Should be pass, pass, fail
print(df["grade"])
df.sort_values("score", ascending=False, inplace=True)

0    Pass
1    Pass
2    Fail
Name: grade, dtype: object
