In [3]:
import numpy as np
from numpy import random
rng = random.default_rng(42)

In [21]:
b = np.array([[1, 2], [3, 4]])
print(b)
print(b[[1, 1], [0, 0]])
print([b[1, 0], b[1, 0]])

[[1 2]
 [3 4]]
[3 3]
[np.int64(3), np.int64(3)]


In [5]:
a = rng.integers(0, 10, (5,5))
a

array([[6, 4, 8, 5, 4],
       [4, 2, 0, 5, 8],
       [0, 8, 8, 2, 6],
       [1, 7, 7, 3, 0],
       [9, 4, 8, 6, 7]])

In [6]:
a = np.array([1, 2, 3])
a = a + 10
a

array([11, 12, 13])